startupClass: eu.nvna.Main
input:
taskDescription: |-
    II. Да се състави клас ColorRectangle в двумерното пространство,
        наследник на клас Color,
        имплементиращ интерфейс Comparable:
        Скрити член променливи, координати - int iX1, iY1, iX2, iY2;
        Публични членове:
        Конструктори:
            1) Подразбиращ се:
            2) Експлицитен – координати и съставен цвят;
        Методи:
            4) четене/запис по 4 get/set
            5) Изчислява/връща площ на правоъгълника int calcArea()
            6) Сравнява с подадения като параметър за "по-малък" по площ -1,0,+1
            int compareTo(ColorRectangle r) или (public int compareTo(Object r))
            7) Стрингова интерпретация на обектите-String toString()
            8)Еквивалентност с подадения параметър-boolean equals(...),
            включително цвят
            9)Изместване по X на подадените точки:
            public void translateX(int iPoints)
            10)Изместване по Y на подадените точки
            public void translateY(int iPoints)
            10)Изместване по X и Y на подадените точки
            11)Точки X и Y в правоъгълника ли са- boolean isInside(int ptX, int ptY )
            12) Изчислява/връща обграждащ правоъгълник между подадения параметър и
            члена
            13) Изчислява/връща общ правоъгълник между подадения параметър и члена